FROM jermine/opencv:aarch64-ubuntu-3.4.1
COPY requirements.txt /app
WORKDIR /app
RUN apt update && apt install -y g++ python3 python3-pip python3-dev libjpeg-dev  liblapack-dev gfortran zlib1g-dev && \
    pip3 install -r requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple/ && \
    wget https://github.com/itdaniher/aarch64-tensorflow/releases/download/v1.5.0/tensorflow-1.5.0-cp36-cp36m-linux_aarch64.whl && \
    pip3 install tensorflow-1.5.0-cp36-cp36m-linux_aarch64.whl -i https://mirrors.ustc.edu.cn/pypi/web/simple && \
    rm -rf ./*

CMD [ "bash" ]
